import type { Metadata } from 'next'
import { Inter, Silkscreen } from 'next/font/google'
import './globals.css'
import localFont from 'next/font/local'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'

const interSans = Inter({
    variable: '--font-inter-sans',
    subsets: ['latin'],
})

// const silkscreen = Silkscreen({
//     variable: '--font-silkscreen-sans',
//     subsets: ['latin'],
//     weight: ['400', '700'],
// })

export const silkscreen = localFont({
    src: [
        {
            path: '../fonts/Silkscreen/Silkscreen.ttf',
            style: 'normal',
        },
    ],
    variable: '--font-silkscreen-sans',
})

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const messages = await getMessages()
    const locale = await getLocale()
    return (
        <html lang={locale}>
            <body
                className={`${interSans.variable} ${silkscreen.variable} antialiased max-w-[1440px] w-full justify-self-center`}
            >
                <NextIntlClientProvider messages={messages} locale={locale}>
                    {children}
                </NextIntlClientProvider>
            </body>
        </html>
    )
}
