import type { Metadata } from 'next'
import { Inter, Silkscreen, Handjet } from 'next/font/google'
import './globals.css'
import localFont from 'next/font/local'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'
import { DotPattern } from '@/components/ui/magicui/dot-pattern'
import DotPatternDemo from '@/components/ui/Background/Background'

const interSans = Inter({
    variable: '--font-inter-sans',
    subsets: ['latin'],
})

const handjet = Handjet({
    variable: '--font-handjet-sans',
    subsets: ['latin'],
    weight: ['400', '700'],
})
const silkscreen = localFont({
    src: [
        {
            path: '../fonts/Silkscreen/Silkscreen.ttf',
            style: 'normal',
        },
    ],
    variable: '--font-silkscreen-sans',
})

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const messages = await getMessages()
    const locale = await getLocale()
    return (
        <html lang={locale}>
            <body
                className={`${interSans.variable} ${silkscreen.variable} ${handjet.variable} antialiased w-full justify-self-center`}
            >
                <div className="absolute  h-full inset-0 w-full min-h-full ">
                    <DotPatternDemo />
                </div>

                <NextIntlClientProvider messages={messages} locale={locale}>
                    {children}
                </NextIntlClientProvider>
            </body>
        </html>
    )
}
